version: "2"
services:
  web:
    build: .
    command: php -S 0.0.0.0:8000 -t /code/wordpress/
    ports:
      - "8080:8000"
    depends_on:
      - db
    volumes:
      - .:/code
  db:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: mysql
